name: job step demo

on: push

jobs:
  demo-job:
    runs-on: ubuntu-latest

    steps:
      - name: step 1 - Print message
        run: echo "This is step 1"

      - name: step 2 - Print message
        run: echo "This is step 2"

      - name: step 3 - Print message
        run: echo "This is step 1 - trigger test"