name: job step demo

on: 
  push:
    branches:
      - main
  pull_request:

jobs:
  frontend-job:
    runs-on: ubuntu-latest

    env:
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      APP_NAME: vprofile
      APP_ENV: dev

    steps: 
      - name: Print environment variables
        run: |
          echo "App Name: $APP_NAME"
          echo "App Environment: $APP_ENV"

      - name: Use secret
        run: |
          echo "DB password is $DB_PASSWORD"
      - name: Frontend task
        run: echo "Running frontend task..."

  backend-job:
    runs-on: ubuntu-latest

    env:
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      APP_NAME: vprofile
      APP_ENV: dev

    steps: 
      - name: Print environment variables
        run: |
          echo "App Name: $APP_NAME"
          echo "App Environment: $APP_ENV"

      - name: Use secret
        run: |
          echo "DB password is $DB_PASSWORD"
      - name: Backend task
        run: echo "Running backtend task..."