name: job step demo

on: 
  push:
    branches:
      - main
  pull_request:

jobs:
  demo-job:
    runs-on: ubuntu-latest

    env:
      APP_NAME: vprofile
      APP_ENV: dev

    steps: 
      - name: Print environment variables
        run: |
          echo "App Name: $APP_NAME"
          echo "App Environment: $APP_ENV"